# Generated by Django 4.1.2 on 2022-10-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
