# Generated by Django 4.1.2 on 2022-10-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="board/images/%Y/%m/%d"),
        ),
    ]
